<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
  </ItemGroup>

  <!-- Versioning & SourceLink -->
  <ItemGroup>
    <GlobalPackageReference Include="DotNet.ReproducibleBuilds" Version="2.0.5" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.301" />
    <GlobalPackageReference Include="MinVer" Version="7.0.0" />
    <GlobalPackageReference Include="ThisAssembly.AssemblyInfo" Version="2.1.2" />
  </ItemGroup>
</Project>
