namespace Pipelines.Generator.Generators.PipelinesRegistration;

internal static class PipelinesRegistrationGenerator
{
    public static void Initialize(in PipelinesGeneratorContext ctx)
    {
        var context = ctx.Context;
        var features = ctx.Features;

        context.RegisterSourceOutput(features, static (spc, features) =>
        {
            if (features is not { HasDependencyInjection: true, DisableMediatorRegistration: false })
                return;

            GenerateSourceOutput(spc);
        });
    }

    private static void GenerateSourceOutput(in SourceProductionContext spc)
    {
        var sb = new SourceBuilder();
        sb.AutoGeneratedCodeHeader();
        sb.Line();
        sb.NullableEnable();
        sb.Line();
        sb.UsingSystemCodeDomCompiler();
        sb.UsingMicrosoftExtensionsDependencyInjection();
        sb.UsingPipelines();
        sb.Line();
        sb.Line("namespace Microsoft.Extensions.DependencyInjection;");
        sb.Line();
        sb.GeneratedCodeAttribute();
        using (sb.Block("internal static partial class PipelinesRegistrations"))
        {
            using (sb.Block(sb, $"public static {sb.IServiceCollection} AddPipelines(this {sb.IServiceCollection} services)"))
            {
                sb.Line("services.TryAddScoped(typeof(global::Pipelines.Requests.RequestPipeline<,>));");
                sb.Line("services.TryAddScoped(typeof(global::Pipelines.Streams.StreamRequestPipeline<,>));");
                sb.Line("services.TryAddScoped<global::Pipelines.Pipeline>();");
                sb.Line();
                sb.Line("return services;");
            }
        }
        sb.Line();
        sb.NullableDisable();
        sb.AddTo(spc, "PipelinesRegistrations.Pipelines.g.cs");
    }
}
