using Pipelines.Generator.Generators.HandlesrRegistration.Models;
using System.Diagnostics.CodeAnalysis;

namespace Pipelines.Generator.Generators.HandlesrRegistration;

internal static class HandlesrRegistrationGenerator
{
    public static void Initialize(PipelinesGeneratorContext ctx)
    {
        var context = ctx.Context;
        var features = ctx.Features;

        var handlers = context
            .SyntaxProvider
            .CreateSyntaxProvider(Predicate, (context, ct) => Transform(context.Node, context.SemanticModel, ct))
            .SelectMany((x, ct) => x)
            .Collect();

        var toGenerate = features
            .Combine(handlers);

        context.RegisterSourceOutput(toGenerate, static (spc, ctx) =>
        {
            var (features, handlers) = ctx;

            if (features is not { HasDependencyInjection: true, DisableHandlerRegistration: false })
                return;

            GenerateSourceOutput(spc, handlers);
        });
    }

    private static bool Predicate(SyntaxNode node, CancellationToken ct)
    {
        return node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 } or RecordDeclarationSyntax { BaseList.Types.Count: > 0 };
    }

    private static IEnumerable<HandlerRegistration> Transform(SyntaxNode node, SemanticModel semanticModel, CancellationToken ct)
    {
        var symbol = node switch
        {
            ClassDeclarationSyntax classSyntax => semanticModel.GetDeclaredSymbol(classSyntax, ct),
            RecordDeclarationSyntax recordSyntax => semanticModel.GetDeclaredSymbol(recordSyntax, ct),
            _ => null
        };

        if (!ValidHandler(symbol))
            yield break;

        foreach (var interfaceSymbol in symbol.AllInterfaces)
        {
            if (IRequestHandler(interfaceSymbol) ||
                IStreamRequestHandler(interfaceSymbol))
            {
                yield return new HandlerRegistration(symbol, interfaceSymbol);
            }
        }

        static bool ValidHandler([NotNullWhen(true)] INamedTypeSymbol? handler) => handler is
        {
            IsAbstract: false,
            IsGenericType: false,
            AllInterfaces.IsEmpty: false,
            IsFileLocal: false,
            DeclaredAccessibility: Accessibility.Public or Accessibility.Internal,
        };

        static bool ValidTypeArgument(ITypeSymbol typeSymbol) => typeSymbol switch
        {
            // todo: expand failure criteria and add diagnostics
            INamedTypeSymbol named => named is
            {
                IsAbstract: false,
                IsFileLocal: false,
                DeclaredAccessibility: Accessibility.Public or Accessibility.Internal,
            },
            _ => true
        };

        static bool IRequestHandler(INamedTypeSymbol handler)
        {
            var result = handler is
            {
                Name: "IRequestHandler",
                IsGenericType: true, TypeParameters.Length: 2, TypeArguments.Length: 2,
                ContainingAssembly.Name: "Pipelines",
            };
            result = result && handler.TypeArguments.All(ValidTypeArgument);
            return result;
        }

        static bool IStreamRequestHandler(INamedTypeSymbol handler)
        {
            var result = handler is
            {
                Name: "IStreamRequestHandler",
                IsGenericType: true, TypeParameters.Length: 2, TypeArguments.Length: 2,
                ContainingAssembly.Name: "Pipelines",
            };
            result = result && handler.TypeArguments.All(ValidTypeArgument);
            return result;
        }
    }

    private static void GenerateSourceOutput(
        in SourceProductionContext spc,
        in ImmutableArray<HandlerRegistration> handlers)
    {
        // todo: diagnostics for duplicate handlers
        //var descriptor = new DiagnosticDescriptor(
        //    id: "TEST01",
        //    title: "A test diagnostic",
        //    messageFormat: "A description about the problem",
        //    category: "tests",
        //    defaultSeverity: DiagnosticSeverity.Warning,
        //    isEnabledByDefault: true
        //);
        //var d = Diagnostic.Create(descriptor, handlersToGenerate[0].Node.GetLocation());
        //spc.ReportDiagnostic(d);

        var sb = new SourceBuilder();
        sb.AutoGeneratedCodeHeader();
        sb.Line();
        sb.NullableEnable();
        sb.Line();
        sb.UsingSystemCodeDomCompiler();
        sb.UsingMicrosoftExtensionsDependencyInjection();
        sb.UsingPipelines();
        sb.Line();
        sb.Line("namespace Microsoft.Extensions.DependencyInjection;");
        sb.Line();
        using (sb.Block("internal static partial class PipelinesRegistrations"))
        {
            using (sb.Block(sb, $"public static {sb.IServiceCollection} AddHandlers(this {sb.IServiceCollection} services)"))
            {
                if (!handlers.IsDefaultOrEmpty)
                {
                    foreach (var handler in handlers)
                    {
                        handler.ServiceRegistration(sb);
                    }
                    sb.Line();
                }
                sb.Line("return services;");
            }
        }
        sb.Line();
        sb.NullableDisable();
        sb.AddTo(spc, "PipelinesRegistrations.Handlers.g.cs");
    }
}
