namespace Pipelines.Generator.Generators;

/// <summary>
/// Provides extension methods for writing standard code. 
/// </summary>
internal static class SourceBuilderExtensions
{
    /// <param name="sb">The <see cref="SourceBuilder"/> instance.</param>
    extension(SourceBuilder sb)
    {
        /// <value>global::Microsoft.Extensions.DependencyInjection.IServiceCollection</value>
        public string IServiceCollection => "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";

        /// <summary>
        /// Writes a using statement for the specified namespace to the source.
        /// </summary>
        /// <param name="using">The namespace to import with the using statement.</param>
        public void Using(string @using)
        {
            sb.Line(sb, $"using {@using};");
        }

        /// <summary>
        /// Writes the auto-generated code header comment indicating that the source code was generated by the Pipelines.Generator source generator.
        /// </summary>
        public void AutoGeneratedCodeHeader()
        {
            const string header = $"""
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This code was generated by the Pipelines.Generator v{ThisAssembly.AssemblyInformationalVersion} source generator.
                //
                //     Changes to this file may cause incorrect behavior and will be lost if
                //     the code is regenerated.
                // </auto-generated>
                //------------------------------------------------------------------------------
                """;
            sb.Line(header);
        }

        /// <summary>
        /// Writes a nullable reference types enable directive (#nullable enable) to the source.
        /// </summary>
        public void NullableEnable()
        {
            sb.Line("#nullable enable");
        }

        /// <summary>
        /// Writes a nullable reference types disable directive (#nullable disable) to the source.
        /// </summary>
        public void NullableDisable()
        {
            sb.Line("#nullable disable");
        }

        /// <summary>
        /// Writes a <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute"/> line with the generator name and version.
        /// </summary>
        public void UsingSystemCodeDomCompiler()
        {
            sb.Line("using global::System.CodeDom.Compiler;");
        }

        /// <summary>
        /// Writes a <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute"/> line with the generator name and version.
        /// </summary>
        public void GeneratedCodeAttribute(bool full = false)
        {
            if (full)
                sb.Line(sb, $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Pipelines.Generator", "{ThisAssembly.AssemblyInformationalVersion}")]""");
            else
                sb.Line(sb, $"""[GeneratedCodeAttribute("Pipelines.Generator", "{ThisAssembly.AssemblyInformationalVersion}")]""");
        }

        /// <summary>
        /// Writes a using statement for the <see cref="global::Microsoft.Extensions.DependencyInjection"/> namespace.
        /// </summary>
        public void UsingMicrosoftExtensionsDependencyInjection()
        {
            sb.Line("using global::Microsoft.Extensions.DependencyInjection;");
            sb.Line("using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        }

        /// <summary>
        /// Writes using statements for the Pipelines, Pipelines.Requests, and Pipelines.Streams namespaces.
        /// </summary>
        public void UsingPipelines()
        {
            sb.Line("using global::Pipelines;");
            sb.Line("using global::Pipelines.Requests;");
            sb.Line("using global::Pipelines.Streams;");
        }
    }
}
