name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+
    paths:
      - src/**
      - Directory.build.packages
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Actions/Checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: NuGet Login
        id: login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Setup .NET
        uses: HereticSoftware/.github/actions/setup-dotnet@3b5813ba304a89237e5c401bff9d50f3b58f8720

      - name: Cake File
        uses: HereticSoftware/.github/actions/cake-file@3b5813ba304a89237e5c401bff9d50f3b58f8720
        env:
          NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
        with:
          target: publish
