name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+
    paths:
      - src/**
      - Directory.build.packages
jobs:
  publish:
    uses: HereticSoftware/.github/.github/workflows/cake-file.yaml@05ac2b1f70f528e70c7083deb26b91818ed06598
    with:
      target: publish
      nuget: true
    secrets:
      nuget-user: ${{ secrets.NUGET_USER }}
