name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - Directory.Packages.props
    types:
      - opened
      - ready_for_review
      - review_requested
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Actions/Checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: HereticSoftware/.github/actions/setup-dotnet@b0e9f8a17bc89c540b6c102adce8440ebac767cc

      - name: Cake File
        uses: HereticSoftware/.github/actions/cake-file@b0e9f8a17bc89c540b6c102adce8440ebac767cc
        with:
          target: pull-request
