name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - Directory.Packages.props
    types:
      - opened
      - ready_for_review
      - review_requested
jobs:
  pull_request:
    uses: HereticSoftware/.github/.github/workflows/cake-file.yaml@05ac2b1f70f528e70c7083deb26b91818ed06598
    with:
      target: pull-request
